/** Curated blocklist (ID + EN). Keep lowercase; matching runs after normalization. */
export const PROFANITY_WORDLIST = [
  "anjing",
  "babi",
  "bangsat",
  "bajingan",
  "kontol",
  "memek",
  "tolol",
  "goblok",
  "bodoh",
  "idiot",
  "fuck",
  "fucking",
  "shit",
  "bitch",
  "bastard",
  "asshole",
  "damn",
  "cunt",
  "dick",
  "pussy",
  "whore",
  "slut",
] as const;
