"use server";

import { z } from "zod";
import { headers } from "next/headers";
import { prisma } from "@/lib/prisma";
import { PurchaseSchema } from "@/lib/schemas";
import { getPurchaseLimiter, getClientIp } from "@/lib/rate-limit";
import { sendPurchaseConfirmation } from "@/lib/email";

export type PurchaseState = {
  success: boolean;
  message?: string;
  errors?: z.inferFlattenedErrors<typeof PurchaseSchema>["fieldErrors"];
};

export async function submitPurchase(
  prevState: PurchaseState,
  formData: FormData,
): Promise<PurchaseState> {
  try {
    const limiter = getPurchaseLimiter();
    if (limiter) {
      const headerList = await headers();
      const ip = getClientIp(headerList);
      const { success } = await limiter.limit(ip);
      if (!success) {
        return {
          success: false,
          message: "Too many purchase attempts. Please try again later.",
        };
      }
    }

    const validatedFields = PurchaseSchema.safeParse({
      productId: formData.get("productId"),
      buyerName: formData.get("buyerName"),
      buyerEmail: formData.get("buyerEmail"),
    });

    if (!validatedFields.success) {
      return {
        success: false,
        errors: validatedFields.error.flatten().fieldErrors,
      };
    }

    const { productId, buyerName, buyerEmail } = validatedFields.data;

    // Check if product exists and is visible
    const product = await prisma.product.findUnique({
      where: { id: productId },
    });

    if (!product || !product.isVisible) {
      return {
        success: false,
        message: "Product not found or unavailable.",
      };
    }

    // Create purchase record
    const expiresAt = new Date();
    expiresAt.setHours(expiresAt.getHours() + 24);

    const purchase = await prisma.purchase.create({
      data: {
        productId,
        buyerName,
        buyerEmail,
        tokenExpiresAt: expiresAt,
        // downloadToken is generated by default cuid()
        // tokenUsed defaults to false
      },
    });

    // Send email
    await sendPurchaseConfirmation({
      name: buyerName,
      email: buyerEmail,
      productName: product.name,
      downloadToken: purchase.downloadToken,
    });

    return {
      success: true,
      message: "Check your email for the download link!",
    };
  } catch (error) {
    console.error("Purchase error:", error);
    return {
      success: false,
      message: "An unexpected error occurred. Please try again later.",
    };
  }
}
