services:
  devixid:
    build:
      context: .
      dockerfile: Dockerfile
    image: devixid_image
    container_name: devixid-container
    env_file:
      - .env
    ports:
      - "5432:5432"

  devixid_dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: devixid-dev_image
    container_name: devixid-dev_container
    env_file:
      - .env.development
    ports:
      - "5432:5432"