services:
  devixid:
    build:
      context: .
      dockerfile: Dockerfile
    image: devixid
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  devixid_dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: devixid_dev
    env_file:
      - .env.development
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
