version: "3.8"
services:
  devixid:
    build:
      context: .
      dockerfile: Dockerfile
    image: devixid
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: devix_admin
  devixid_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: devixid_dev
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: devix_admin_dev
