/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DashboardIndexImport } from "./routes/dashboard/index";

// Create Virtual Routes

const SigninLazyImport = createFileRoute("/signin")();
const DashboardPortfolioLazyImport = createFileRoute("/dashboard/portfolio")();

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: "/signin",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/signin.lazy").then((d) => d.Route));

const DashboardIndexRoute = DashboardIndexImport.update({
  path: "/dashboard/",
  getParentRoute: () => rootRoute,
} as any);

const DashboardPortfolioLazyRoute = DashboardPortfolioLazyImport.update({
  path: "/dashboard/portfolio",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/dashboard/portfolio.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/portfolio": {
      id: "/dashboard/portfolio";
      path: "/dashboard/portfolio";
      fullPath: "/dashboard/portfolio";
      preLoaderRoute: typeof DashboardPortfolioLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  SigninLazyRoute,
  DashboardPortfolioLazyRoute,
  DashboardIndexRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/signin",
        "/dashboard/portfolio",
        "/dashboard/"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/dashboard/portfolio": {
      "filePath": "dashboard/portfolio.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
