name: Build Backend Docker Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'apps/backend/**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: apps/backend
        run: docker-compose build --pull --no-cache 
