name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "apps/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: apps/backend
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
